### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by rovertdude** [rovertdude/PugFreedomMod#47]
We might make one of @DUFCLiam or @adroition a collaborator.
Looking for replies.

**Comment by PuggyCrew** [comment]
@DUFCLiam is new to collaborating to the Pug Freedom Mod.
@adroition should be a new collaborator for now seeing he has made quite a few pull requests.

**Comment by DUFCLiam** [comment]
I wanna be colab xD

**Comment by rovertdude** [comment]
@adroition didn't make any commands.
@DUFCLiam should probably get it.

**Comment by ownre** [comment]
I think @DUFCLiam should get it; he seems good for it.

**Comment by DUFCLiam** [comment]
Ask me something to make =D

**Comment by adroition** [comment]
As @PuggyCrew said, I made no commands.
@DUFCLiam made some and can probably make more.

**Comment by adroition** [comment]
@DUFCLiam or @ownre should be it.

**Comment by rovertdude** [comment]
Most favor seems to be to @DUFCLiam 
I'm adding him as the new collaborator and denying the removal of him from the dev list.

**Comment by DUFCLiam** [comment]
Thank you :) @rovertdude
