### ISSUE TITLE
Possible new idea

### ISSUE THREAD

**Issue by adroition** [rovertdude/PugFreedomMod#63]
I don't have the code for these commands, but this is what I thought of:

/emf
/ai
/seniorchat [/sc alias]
/list -o (List's owners)
/sys doom (/doom only in /sys)
/sys wipeflatlands (/wipeflatlands in /sys)
/sys teston will enable adminmode

**Comment by rovertdude** [comment]
This seems interesting, we don't need /sys doom as we have /sys suspend, but the others seem interesting.

**Comment by rovertdude** [comment]
lol

**Comment by DUFCLiam** [comment]
There xD

**Comment by rovertdude** [comment]
I'm not too sure of how to make any of those anyways.

**Comment by DUFCLiam** [comment]
#Liam4Owner in GitHub plz xD

**Comment by rovertdude** [comment]
nopls

**Comment by ownre** [comment]
I am attempting these commands:
/emf
/ai
/list -o
/sys teston [adminmode]

**Comment by DUFCLiam** [comment]
`/emf` you cannot do as this is from AcidFreedom
`/ai` is implemented due to this being TFM fork
`list -o` Good to go
`sys teston [adminmode]` Not needed but good to go

**Comment by ownre** [comment]
/emf is not copyrighted like that.
If I CUSTOM CODE a /emf, I have full rights  to /emf.

**Comment by DUFCLiam** [comment]
I never said implementation was not permitted but I had my say.

**Comment by FoxIshDaBest** [comment]
Isnt Senior admin chat already a thing?

**Comment by DUFCLiam** [comment]
I think so not to sure @FoxIshDaBest I came in Late development

**Comment by DUFCLiam** [comment]
Too long to complete task see: #insert new link once created

**Comment by rovertdude** [comment]
If it takes too long, just close it; don't just straight up deny it. If we deny it, we have to remove the PR's.
