### ISSUE TITLE
Chat {TALK HERE}

### ISSUE THREAD

**Issue by DUFCLiam** [rovertdude/PugFreedomMod#64]

**Comment by DUFCLiam** [comment]
@rovertdude Hiyaaa

**Comment by rovertdude** [comment]
@PuggyCrew 
Explain why you did this:
(description = "Kicks everyone and stops the server.", usage = "/<command>", aliases = "toggle")

**Comment by rovertdude** [comment]
xD

**Comment by rovertdude** [comment]
I'm removing him from collaborators.

**Comment by PuggyCrew** [comment]
bitch please

**Comment by DUFCLiam** [comment]
Who? And why?

**Comment by rovertdude** [comment]
He added this to /stop:
(description = "Kicks everyone and stops the server.", usage = "/<command>", aliases = "toggle")

aliases = "toggle")

**Comment by rovertdude** [comment]
I removed @PuggyCrew from collaborators as he made toggle an alias of /stop

**Comment by DUFCLiam** [comment]
That's why then...

**Comment by rovertdude** [comment]
@DUFCLiam 
@adroition made you developer on the forums.

**Comment by DUFCLiam** [comment]
Thanks

**Comment by rovertdude** [comment]
@DUFCLiam
I'm making a PFM server again - the ip if you want is pugfreedommod.g-s.nu
