### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by adroition** [rovertdude/PugFreedomMod#74]
#73 
Excuse me?
You have no right to lock that.
What is your valid reasoning for locking it?
@DUFCLiam 
@rovertdude

**Comment by adroition** [comment]
Kindly explain why you denied a PR that rovertdude accepted.

**Comment by DUFCLiam** [comment]
I do not have to explain to you but I am going to, It was an invalid thread
@adroition do not make threads like this, Also I have right to believe you are related/an alias of @PuggyCrew

**Comment by rovertdude** [comment]
@PuggyCrew and @adroition are separate people.
I have met both of them in real life before.

**Comment by ownre** [comment]
This is more worth a warning.

**Comment by DUFCLiam** [comment]
@ownre Give a reason why I should be warned?

**Comment by ownre** [comment]
@DUFCLiam For the reasons said in #73

**Comment by ownre** [comment]
A warning is nothing to be ashamed about; it's all about learning about it.
