### ISSUE TITLE
adroition

### ISSUE THREAD

**Issue by rovertdude** [rovertdude/PugFreedomMod#75]
I'm temporarily making @adroition a collaborator.

**Comment by DUFCLiam** [comment]
Ok, Make sure there is no abuse from any member of this team, also @adroition has been making posts like this: #74 and #73 also because of the way these are I think @PuggyCrew is an alias of @adroition or the other way around

**Comment by rovertdude** [comment]
As I said in #74 I have met both of them in real life together.

**Comment by DUFCLiam** [comment]
I seen, therefore I did not reply.
