### ISSUE TITLE
Lockdown

### ISSUE THREAD

**Issue by adroition** [rovertdude/PugFreedomMod#8]
/toggle is completely broken.

**Comment by rovertdude** [comment]
So apparently it's broken again.

**Comment by DUFCLiam** [comment]
You do `/toggle lockdown` so invalid

**Comment by rovertdude** [comment]
OP's are the only ones able to use /toggle as I am testing

**Comment by rovertdude** [comment]
I've confirmed it right now.

**Comment by DUFCLiam** [comment]
Wait, there is a server? xD

**Comment by rovertdude** [comment]
I'm testing it on a local server right now

**Comment by DUFCLiam** [comment]
Ahhhh

**Comment by rovertdude** [comment]
/toggle is acting up for some reason

**Comment by DUFCLiam** [comment]
Send me logs.

**Comment by rovertdude** [comment]
I can't, when I use /toggle the server completely shuts down.

**Comment by DUFCLiam** [comment]
Oh....
Try `/toggle lockdown`

**Comment by rovertdude** [comment]
That seems to work, but it let me use it as a OP

**Comment by DUFCLiam** [comment]
Will try to fix that now.

**Comment by rovertdude** [comment]
Found out why

**Comment by rovertdude** [comment]
looks like @PuggyCrew has some explaining with it

**Comment by DUFCLiam** [comment]
What?
