### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by DUFCLiam** [rovertdude/PugFreedomMod#81]
I will add these features
- [x]  **_Bugs_**:
   - [x] Fix tban (So they cannot just rejoin)

- [x]  **_Features_**:
    - [x] /emf - Smites/Kills them then messages the user "ENGLISH YOU SPEAK IT!"
    - [ ] /seniorchat  - It only lets seniors talk to each other (No super admins also would be insecure if people have panel or BukkitTelnet as they can review all commands) [/sc - As an alias]
    - [ ] PugFreedom (Info Command)
    - [ ] Set & Delete login title commands
    - [ ] warn, del warnings and get warnings (Under one "Warnings command?)
    - [ ] hidemyass (gm 3 command / vanish command)
    - [x] kick (Fully working)
    - [ ] report (Maybe actually open trackable issues this time they can only use report once a time)

**Comment by DUFCLiam** [comment]
Do  not close open issues

**Comment by DUFCLiam** [comment]
That another collaborator  has made without a good reason

**Comment by FoxIshDaBest** [comment]
k. Doesn't need a pull request if your just going to do it yourself...

**Comment by DUFCLiam** [comment]
Just wanted to show and get comments/suggestions

**Comment by DUFCLiam** [comment]
Also other people can make a pull request and use this as the issue if it completed one of the unchecked boxes!
