### ISSUE TITLE
Stealing my repo.

### ISSUE THREAD

**Issue by Sven65** [rovertdude/PugFreedomMod#85]
I saw that you stole my repository, (RPGBot).
I say stole because you forked it without my explicit permission, wich in the README.md file, it clearly states that you need.
I post this as an issue due to you not providing any other means of contact.
Please delete your repository that you forked from my work.

Thanks.

**Comment by rovertdude** [comment]
I don't need it anyways

**Comment by Sven65** [comment]
Thank you.
